name: Deployment [Dev]

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: dev-test:latest
        file: ./Dockerfile
        outputs: type=docker,dest=/tmp/test-image.tar
        
    - name: Ls
      run: ls -l /tmp
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dev-image
        path: /tmp/test-image.tar

