name: Deployment [Dev]

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build -f Dockerfile -t dev-sim:build .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-sim
        path: /tmp/dev-sim.tar
