name: Deployment [Dev]

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        tags: dev-django:latest
        push: false
        outputs: type=docker,dest=/tmp/django-image.tar
      env:
        DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        DOCKER_BUILD_SUMMARY: false
        DOCKER_BUILD_RECORD_RETENTION_DAYS: 3
        
    - name: Ls
      run: ls -l /tmp
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-django-image
        path: /tmp/django-image.tar

