name: Deployment [Dev]

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  scan-secrets:
    name: Find secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified


  build-django:
    name: Build Image
    needs: scan-secrets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        tags: dev-django:latest
        push: false
        outputs: type=docker,dest=/tmp/django-image.tar
      env:
        DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        DOCKER_BUILD_SUMMARY: false
        DOCKER_BUILD_RECORD_RETENTION_DAYS: 3
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-django-image
        path: /tmp/django-image.tar


  image-scan:
    name: Image scan
    needs: build-django
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dev-django-image
        path: /tmp/

    - name: Load image
      run: |
        docker load --input /tmp/django-image.tar
    
    - name: Run Trivy vulnerability scanner on django
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'dev-django:latest'
        format: 'table'
        ignore-unfixed: true
        exit-code: '1'
        vuln-type: 'os,library'
#        severity: 'CRITICAL,HIGH'

